spring.application.name=casestudy

spring.datasource.url=jdbc:postgresql://localhost:5432/myappdb
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.docker.compose.file=docker-compose.yml
spring.docker.compose.lifecycle-management=start-only
